name: contact_picker
description: A Flutter plugin for picking a contact from the address book.
version: 0.0.2
homepage: https://github.com/goderbauer/contact_picker

flutter:
  plugin:
    androidPackage: net.goderbauer.flutter.contactpicker
    pluginClass: ContactPickerPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <4.0.0"
